#!/usr/bin/env python3

import argparse
import docker
import subprocess
import os

IMAGE_NAME: str = 'colajam93/yay'
CONTAINER_NAME: str = 'yaourt_cookie'
PACKAGE_DIR: str = os.getcwd()


def space_join(gen):
    return ' '.join(gen)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('package', nargs='+')
    parser.add_argument('-e', '--extra-command', action='append')
    args = parser.parse_args()

    if args.extra_command:
        extra_command = args.extra_command
    else:
        extra_command = []

    client = docker.from_env()

    try:
        client.images.get(IMAGE_NAME)
    except docker.errors.ImageNotFound:
        subprocess.run(['docker', 'pull', IMAGE_NAME])
    build_command = ['/usr/bin/yay', '--noconfirm', '-S']
    build_command += args.package
    commands = ' && '.join(extra_command + [space_join(build_command)])
    client.containers.run(
        IMAGE_NAME,
        command=f"/usr/bin/bash -c '{commands}'",
        name=CONTAINER_NAME,
        remove=True,
        volumes={PACKAGE_DIR: {
            'bind': '/home/user/pkg',
            'mode': 'rw'
        }})


if __name__ == '__main__':
    main()
